FROM python:3.10-slim

WORKDIR /app

COPY requirements-streamlit.txt .

RUN pip install --no-cache-dir -r requirements-streamlit.txt

COPY streamlit_ui ./streamlit_ui

EXPOSE 8080

CMD ["streamlit","run","streamlit_ui/Streamlitapp.py","--server.port=8080","--server.address=0.0.0.0"]
