FROM python:3.10-slim

WORKDIR /app

COPY requirements-streamlit.txt .

RUN pip install --no-cache-dir -r requirements-streamlit.txt

COPY streamlit_ui ./streamlit_ui

CMD streamlit run streamlit_ui/StreamlitApp.py --server.port $PORT --server.address 0.0.0.0 --server.enableCORS false --server.enableXsrfProtection false
