from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Literal


ContentType = Literal["text", "table", "csv_row", "chart", "diagram", "figure", "image"]


@dataclass(slots=True)
class ContentBlock:
    """A semantic unit from a source document before final chunking."""

    text: str
    type: ContentType = "text"
    page: int | None = None
    source_path: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class ExtractedImage:
    """A detected visual region from a PDF."""

    image_path: Path
    page: int | None
    type: ContentType = "figure"
    source_path: str = ""
    element_id: str = ""
    coordinates: dict[str, Any] = field(default_factory=dict)
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class VisionDescription:
    """Structured output generated by the vision model for one visual block."""

    image_path: Path
    description: str
    page: int | None = None
    type: ContentType = "chart"
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class EnrichedDocument:
    """Markdown plus retrieval metadata after text, table, CSV, and visual enrichment."""

    source_path: str
    markdown: str
    blocks: list[ContentBlock] = field(default_factory=list)
    images: list[ExtractedImage] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class Chunk:
    """A final embedding-ready unit."""

    text: str
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class IngestionResult:
    """End-to-end ingestion output."""

    enriched_document: EnrichedDocument
    chunks: list[Chunk]
    metadata: dict[str, Any] = field(default_factory=dict)
