name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libpcre2-dev libpcre3-dev

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel pypcre
        pip install "torch>=2.7.1" --extra-index-url https://download.pytorch.org/whl/cpu
        pip install gptqmodel --no-build-isolation
        pip install --prefer-binary -r requirements.txt
    - name: Run Pytest Evaluation Suite
      run: |
        pytest
